name: Move new issues into Triage

on:
  issues:
    types: [assigned]

jobs:
  automate-project-columns:
    runs-on: macos-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Docs-Work
          column: In progress
          repo-token: ${{ secrets.DOCS_API_KEY }}
