name: Move assigned card
on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Move to In Progress
      uses: kin/gh-action-move-issue-to-column@1.0
       with:
          project-name:: "Docs-Work"
          target-column: "In Progress"
          access-token: "#{{ secrets.GITHUB_TOKEN }}"	  
