
on:
  issues:
    types: [assigned]

jobs:
  move-to-in-progress:
    runs-on: MACOS-latest
    name: Move to In Progress Column
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Move to In Progress
        uses: kin/gh-action-move-issue-to-column@1.0
        with:
          access-token: "#{{ secrets.DOCS_API_KEY }}"
          project-name: "Backlog"
          target-column: "In Progress"
