
on:
  issues:
    types: [assigned]

jobs:
  move-to-in-progress:
    runs-on: MACOS-latest
    name: Move to In Progress Column
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Move Issues to Column
        uses: kin/gh-action-move-issues-to-column@v1.0
        with:
          access-token: "#{{ secrets.GITHUB_TOKEN }}"
          project-name: "Backlog"
          target-column: "In Progress"
