name: Move new issues into Triage

on:
  issues:
    types: [assigned]

jobs:
  automate-project-columns:
    runs-on: macos-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: Backlog
          column: In progress
          repo-token: ${{ secrets.DOCS_API_KEY }}
